---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation: 
    widescreen: yes
    self_contained: no
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
```
## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
heartrate <- read_csv("data/heartrate.csv")
```
```{r}
heartrate
```
```{r}
names(heartrate)
```

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate %>% 
  ggplot(aes(x=patient, y=a)) +
  geom_col()+
  labs(title = "Patients Response to Drug A",
       x = "Patients",
       y = "Drug A") +
  theme(plot.title = element_text(size = rel(1.2), hjust = 0.4))
```


```{r}
heartrate %>% 
  ggplot(aes(x=patient, y=a)) +
  geom_point() +
  geom_smooth(method=lm, se=F) +
  labs(title = "Patients Response to Drug A",
       x = "Patients",
       y = "Drug A") +
  theme(plot.title = element_text(size = rel(1.2), hjust = 0.4))
# my code
```

2. Make a plot that compares heartrate (as a range) for each drug.

```{r}
# Insert code discussed in class
```











